
FROM busybox AS bun
ARG BUN_URL="https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"
RUN wget -q ${BUN_URL} -O ./bun-linux-x64.zip \
  && unzip ./bun-linux-x64.zip -d ./

FROM quay.io/fedora/fedora-toolbox:41 AS Release

ARG NAME=toolbox

LABEL name="$NAME" \
  summary="Fedora toolbox container" \
  maintainer="Joe Terlecki"

ENV EDITOR=nvim

COPY --from=bun /bun-linux-x64/bun /usr/local/bin
COPY ./yum.repos.d/*.repo /etc/yum.repos.d/

RUN dnf -y upgrade \
  && dnf -y install \
  ripgrep \
  neovim \
  zsh \
  awscli \
  terraform \
  dotnet-sdk-8.0 \
  golang \
  go-task \ 
  bat \
  lsd \
  zoxide \
  fzf \
  && dnf clean all
