FROM quay.io/fedora/fedora-toolbox:41

ARG NAME=toolbox

LABEL name="$NAME" \
      summary="Fedora toolbox container" \
      maintainer="Joe Terlecki"

ENV EDITOR=nvim

# Install packages
RUN dnf -y upgrade \
  && dnf -y install \
  ripgrep \
  && dnf clean all
