FROM quay.io/fedora-ostree-desktops/base-atomic:41 as release

ARG WEZTERM_URL="https://github.com/wezterm/wezterm/releases/download/20240203-110809-5046fc22/wezterm-20240203_110809_5046fc22-1.fedora39.x86_64.rpm"

RUN echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-ip-forward.conf && \
    echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.d/99-ip-forward.conf

COPY ./yum.repos.d/*.repo /etc/yum.repos.d/

RUN rpm-ostree install \
    tailscale \
    zsh \
    i3 \
    i3lock \
    i3status \
    lightdm \
    lightdm-greeter \
    lightdm-gtk-greeter-settings \
    network-manager-applet \
    pavucontrol \
    pulseaudio-utils \
    volumeicon \
    azote \
    firefox \
    thunar \
    dmenu \
    polybar \
    rofi \
    feh \
    mousepad \
    htop \
    dunst \
    light \
    NetworkManager \
    brightnessctl \
    lightdm \
    lxappearance \
    ${WEZTERM_URL} \
    glx-utils \
    mesa-dri-drivers \
    mesa-vulkan-drivers \
    plymouth-system-theme \
    xorg-x11-drv-amdgpu \
    xorg-x11-drv-ati \
    xorg-x11-drv-evdev \
    xorg-x11-drv-intel \
    xorg-x11-drv-libinput \
    xorg-x11-drv-nouveau \
    xorg-x11-drv-openchrome \
    xorg-x11-drv-qxl \
    xorg-x11-drv-vmware \
    xorg-x11-drv-wacom \
    xorg-x11-server-Xorg \
    xorg-x11-xauth \
    xorg-x11-xinit \
    && rpm-ostree cleanup -m \
    && ostree container commit

LABEL name="$NAME" \
    summary="Fedora Silverblue SWAY container" \
    maintainer="Joe Terlecki"
