variables:
  IMAGE_NAME: fedora-silverblue-werkstation

stages:
  - build

buildah-build:
  stage: build
  script:
    - apt-get install buildah -y
    - buildah bud -f Containerfile -t "${IMAGE_NAME}" .
    - buildah tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
