variables:
  IMAGE_NAME: fedora-silverblue-werkstation

stages:
  - build

buildah-build:
  stage: build
  image: docker:25-cli
  variables:
    IMAGE_NAME: fedora-silverblue-werkstation
  services:
    - docker:25-dind
  script:
    - docker build -t ${IMAGE_NAME}:latest .

