variables:
  IMAGE_NAME: fedora-silverblue-werkstation

stages:
  - build

buildah-build:
  stage: build
  image:
    name: quay.io/buildah/stable:latest
  variables:
    BUILDAH_FORMAT: oci
  services:
  script:
    - buildah bud -f Containerfile -t "${IMAGE_NAME}"
    - buildah images
    - buildah tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
    - buildah push "${IMAGE_NAME}:latest" oci:./current-image.tar

