variables:
  IMAGE_NAME: fedora-silverblue-werkstation

stages:
  - build

buildah-build:
  stage: build
  image:
    name: buildah/buildah:latest
  variables:
  services:
    - docker:25-dind
  script:
    - docker build -t ${IMAGE_NAME}:latest

