stages:
  - linting
  - build
  - deploy

lint-containerfile:
  stage: linting
  image:
    name: aquasec/trivy
    entrypoint: [""]
  script:
    - trivy fs --scanners misconfig .

buildah-build:
  stage: build
  image:
    name: buildah/buildah
  script:
    - buildah bud -f Containerfile -t fedora-silverblue-werkstation
    - buildah tag fedora-silverblue-werkstation fedora-silverblue-werkstation:latest
