variables:
  IMAGE_NAME: fedora-silverblue-werkstation

stages:
  - build

buildah-build:
  stage: build
  image:
    name: quay.io/buildah/stable:latest
  variables:
    IMAGE_NAME: fedora-silverblue-werkstation
  services:
  script:
    - buildah bud -f Containerfile -t "${IMAGE_NAME}"

