FROM quay.io/fedora-ostree-desktops/sway-atomic:41

RUN set -ex \
    && ZELLIJ_LATEST=$(curl -s https://api.github.com/repos/zellij-org/zellij/releases/latest | grep "tag_name" | cut -d '"' -f 4) \
    && wget -q "https://github.com/zellij-org/zellij/releases/download/${ZELLIJ_LATEST}/zellij-x86_64-unknown-linux-musl.tar.gz" \
    && mkdir -p /tmp/zellij \
    && tar -xzf zellij-x86_64-unknown-linux-musl.tar.gz -C /tmp/zellij \
    && cp /tmp/zellij/zellij /usr/bin/

RUN set -ex \
    && NVIM_LATEST=$(curl -s https://api.github.com/repos/neovim/neovim/releases/latest | grep "tag_name" | cut -d '"' -f 4) \
    && wget -q "https://github.com/neovim/neovim/releases/download/${NVIM_LATEST}/nvim-linux-x86_64.tar.gz" \
    && mkdir -p /tmp/nvim \
    && tar -xzf nvim-linux-x86_64.tar.gz -C /tmp/nvim --strip-components=1 \
    && cp /tmp/nvim/bin/nvim /usr/bin/nvim \
    && cp -r /tmp/nvim/lib/nvim /usr/lib/ \
    && cp -r /tmp/nvim/share /usr/share/

COPY ./yum.repos.d/*.repo /etc/yum.repos.d/

RUN rpm-ostree override remove firefox firefox-langpacks && \
    rpm-ostree install \
    https://github.com/wezterm/wezterm/releases/download/20240203-110809-5046fc22/wezterm-20240203_110809_5046fc22-1.fedora39.x86_64.rpm \
    tailscale alacritty zsh && \
    rpm-ostree cleanup -m && \
    ostree container commit

