FROM quay.io/fedora-ostree-desktops/sway-atomic:41

COPY ./yum.repos.d/*.repo /etc/yum.repos.d/

RUN rpm-ostree override remove firefox firefox-langpacks && \
    rpm-ostree install \
    https://github.com/wezterm/wezterm/releases/download/20240203-110809-5046fc22/wezterm-20240203_110809_5046fc22-1.fedora39.x86_64.rpm \
    tailscale neovim vim tmux && \
    rpm-ostree cleanup -m && \
    ostree container commit

