---
name: Build Werkstation OCI
on:
  - push

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Buildah Biuld
      uses: redhat-actions/buildah-build@v2
      with:
        image: werkstation
        tags:  v1${{ github.sha }}
        context: ./base/
        layers: true
        oci: true
        containerfiles: |
          ./base/Containerfile
        build-args: |


